Fix systemd build with diod.spec, suggestion to split package in diod{,-tuils
chaos/diod pull request #63
Opened 2021-03-13 18:21 UTC by joeydumont

2021-03-13 19:00 UTC, garlick requested changes
No problem with the spec file changes for now.  I can't really test them at the moment, and in fact in some of my other projects, I've dropped the packaging files because I've received conflicting, hard to test changes, and I feel it's not really the upstream project's problem to create portable spec files.  However, we'll go with "whoever touched it last" here for now :-)

In addition to the one change I called out, I would appreciate if you would put the Makefile.am change in one commit and the spec file change in another, then use a 50 char or less summary as the first line of the commit message.  Further commit message detail can continue on in paragraphs after the summary, if needed.

The spec file commit message should probably mention what the specific problem is that you are fixing and on what distro + version.

Feel free to force push those changes to this PR.

2021-03-13 19:00 UTC, garlick commented on configure.ac
> +        m4_esyscmd([git describe --tags | awk '/.*/ {sub(/^v/, ""); printf "%s",$1; exit}']))
I actually do prefer to use `--always` here so that building from a source tree that does not exactly match the latest tag can be detected.

2021-03-13 19:30 UTC, joeydumont commented
Will do! 

The Makefile change is motivated by the spec file fix it the first commit, as the verify phase of rpmbuild got tripped up by the double slash. I can split the changes regardless, if you prefer.

2021-03-13 19:50 UTC, garlick commented
Oh, I didn't realize it was related.  Either way is OK.  Thanks!

2021-03-14 02:56 UTC, joeydumont commented on configure.ac
> +        m4_esyscmd([git describe --tags | awk '/.*/ {sub(/^v/, ""); printf "%s",$1; exit}']))
Ok, I'll revert. I had trouble when I was building, as the only tag that was detected was a very old one. Maybe my tag wasn't annotated? Either way I'll revert.

2021-03-26 01:54 UTC, joeydumont commented
Did you want any more changes to this PR?

2021-03-26 02:00 UTC, merged

2021-03-26 02:00 UTC, garlick commented
Sorry to leave you hanging!  I lost track of this.  Cheers.